name: nokhte
description: A new Flutter project.
publish_to: "none"

version: 2.75.0+142087115

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  action_slider: ^0.7.0
  android_package_manager: ^0.7.1
  blur: ^3.1.0
  carousel_slider: ^5.0.0
  connectivity_plus: ^5.0.1
  crypto: ^3.0.3
  cupertino_icons: ^1.0.8
  dartz: ^0.10.1
  equatable: ^2.0.5
  extended_text_field: ^14.0.1
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_hooks: ^0.20.3
  flutter_mobx: ^2.2.0
  flutter_modular: ^6.3.2
  flutter_slidable: ^3.1.1
  google_fonts: ^5.1.0
  gradient_borders: ^1.0.0
  mobx: ^2.2.1
  nokhte_backend:
    path: ../backend/dart
  package_info_plus: ^8.0.0
  permission_handler: ^11.0.0
  posthog_flutter: ^4.4.1
  sign_in_button: ^3.2.0
  sign_in_with_apple: ^5.0.0
  simple_animations: ^5.0.2
  supabase_flutter: ^2.7.0
  toastification: ^2.3.0
  url_launcher: ^6.3.1

dev_dependencies:
  build_runner: ^2.4.9
  fake_async: ^1.3.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  logger: ^2.0.2+1
  mobx_codegen: ^2.2.0
  mockito: ^5.4.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/article/flexible_seating.png
    - assets/article/strict_seating.png

    - assets/groups/storage_icon.png
    - assets/groups/queue_icon.png
    - assets/groups/add_remove_icon.png
    - assets/groups/trash_icon_white.png
    - assets/groups/user_icon.png
    - assets/groups/settings_icon.png
    - assets/groups/envelope_icon.png
    - assets/groups/plus_icon.png
    - assets/groups/pencil_icon_white.png
    - assets/groups/pencil_icon_black.png
    - assets/groups/envelope_icon_transparent.png
    - assets/groups/magnifying_glass_icon.png

    - assets/docs/trash_icon.png
    - assets/docs/archive_icon.png
    - assets/docs/ellipse_icon.png

    - assets/blocks/conclusion_icon.png
    - assets/blocks/conclusion_send_icon.png
    - assets/blocks/idea_icon.png
    - assets/blocks/idea_send_icon.png
    - assets/blocks/nokhte_icon.png
    - assets/blocks/purpose_icon.png
    - assets/blocks/purpose_send_icon.png
    - assets/blocks/question_icon.png
    - assets/blocks/question_send_icon.png
    - assets/blocks/quotation_icon.png
    - assets/blocks/quotation_send_icon.png

    - assets/home/camera_icon.png
    - assets/home/qr_code_icon.png

    - assets/information/cook_icon.png
    - assets/information/pencil_icon.png
    - assets/information/rally_icon.png

    - assets/login/apple_icon.png
    - assets/login/google_icon.png
    - assets/login/header.png

    - assets/power_up/cook_button.png
    - assets/power_up/rally_button.png

    - assets/session/rounded_triangle.png
    - assets/session/home_beach_icon.png
    - assets/session/end_session_icon.png
    - assets/session/session_information_icon.png
    - assets/session/pause_icon.png
    - assets/session/pencil_icon.png
    - assets/session/trash_icon_black.png

flutter_icons:
  android: true
  ios: true
