name: nokhte_backend
description: A sample command-line application.
version: 1.1.1
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  intl: ^0.20.0
  supabase_flutter: ^2.5.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^3.0.0
