flutter test test/01_user_information_table_test.dart
flutter test test/01.5_user_information_table_test.dart
flutter test test/02_group_information_table_test.dart
flutter test test/03_active_sessions_pair_table_test.dart 
flutter test test/04_finished_sessions_table_test.dart
flutter test test/05_company_presets_table_test.dart
flutter test test/06_company_presets_preferences_table_test.dart